config/routes.rb
Repofinder::Application.routes.draw do
  
  resources :repo
  get 'repo/:owner/:name' => 'repo#show'
  
  resources :category, only: [:index, :show, :create]
  
  post 'tag' => 'tag#create'
  delete 'tag' => 'tag#destroy'

  
  get 'addrepo' => 'repo#create'
  

  root to: "category#index"

end

app/models/repo.rb
class Repo < ActiveRecord::Base
  
  validates :owner, :name, presence: true
  validates :ident, uniqueness: true
  
  acts_as_taggable_on :categories, :frameworks, :languages
  
  protected
  
  def self.init_repo(repo_id)
    repo = Repo.find(repo_id)
    github_api_url = "https://api.github.com/repos/"
    
    github = JSON.parse(Curl::Easy.perform(github_api_url + repo.owner + "/" + repo.name).body_str)
    if github["message"] == "Not Found"
      repo.destroy
      return false
    else
      %w{name description watchers forks html_url homepage}.each do |field|
          repo[field] = github[field]
      end
      repo["owner"] = github["owner"]["login"]
      repo["last_updated"] = github["updated_at"]
      repo["ident"] = github["owner"]["login"] + "/" + github["name"]
      # Repo speichern
      repo.save
      return true
    end
  end
  
  def self.update_repos
    repos = Repo.all
    github_api_url = "https://api.github.com/repos/"
  
    repos.each do |repo|
      github = JSON.parse(Curl::Easy.perform(github_api_url + repo.owner + "/" + repo.name).body_str)
      %w{name description watchers forks html_url homepage}.each do |field|
        repo[field] = github[field]
      end
      repo["owner"] = github["owner"]["login"]
      repo["last_updated"] = github["updated_at"]
      # Repo speichern
      repo.save
    end
    
    puts "Repo.update_repos successfully finished."
  end
    
end

app/controllers/repo_controller.rb
class RepoController < ApplicationController
  
  # GET /repo
  def index
    @repos = Repo.order("watchers DESC")
    
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /repo/1
  def show
    if params[:id]
      @repo = Repo.find_by_id(params[:id])
      note = params[:id].to_s
    elsif (params[:owner] and params[:name])
      @repo = Repo.find_by_owner_and_name(params[:owner].strip, params[:name].strip)
      note = params[:owner].strip + "/" + params[:name].strip
    end
    
    unless @repo.nil?
      @alternatives = @repo.find_related_categories
    end
    
    respond_to do |format|
      format.html {
        if @repo.nil?
          redirect_to :root, notice: "Repo '#{note}' not found."
        else
          # show.html.erb
        end
        }
    end
  end

  # GET /repo/new
  def new
    @repo = Repo.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /repo/1/edit
  def edit
    @repo = Repo.find(params[:id])
  end
  
    # POST /repo
  def create
    # Create an empty repo in memory
    repo = Repo.new
    
    # Var. 1) Github Repo posted to "/addrepo?url="
    if params[:url]
      url = params[:url]
      # Strip url of leading or trailing whitespace
      # Gsub part of url that is not nescessary
      ident = url.gsub("https://github.com/", "").strip
    
      # Split repo ident
      repo.owner = ident.split("/")[0]
      repo.name = ident.split("/")[1]
      repo.ident = ident
    end
  
    # Var. 2) Github Repo is being added by posting to "/repo" through form
    if params[:repo]
      # Remove leading and trialing whitespace
      repo.owner = params[:repo][:owner].strip
      repo.name = params[:repo][:name].strip
      repo.ident = repo.owner + "/" + repo.name
    end
    
    respond_to do |format|
      if Repo.find_by_ident(repo.ident).nil?
        # Repo is not yet listed
        
        if repo.save # check validation
        
          # Validations passed
          if Repo.init_repo(repo.id)
            # Repo could be found on Github
            format.html { redirect_to "/repo/#{repo.id}", notice: ":-) The repo '#{repo.owner}/#{repo.name}' has been successfully added. Thanks for helping to improve this site!" }
          else
            # Repo could not be found on Github and was deleted
            format.html { redirect_to root_url, notice: "The repo '#{repo.owner}/#{repo.name} could not be found on Github. Please try again."}
          end
        
        else
          # Validation failed
          format.html { redirect_to root_url, notice: "Error. Please provide the repo owner and name on Github once again." }
        end
        
      else
        # Repo already listed 
        repo = Repo.find_by_ident(repo.ident) 
        format.html { redirect_to "/repo/#{repo.id}", notice: "Error. The repo '#{repo.owner}/#{repo.name}' is already listed. Maybe you'd like to tag it! Thanks for your help!"}
      end
      
    end
    
  end # create

  # PUT /repo/1
  def update
    @repo = Repo.find(params[:id])

    respond_to do |format|
      if @repo.update_attributes(params[:repo])
        format.html { redirect_to @repo, notice: 'Repo was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /repo/1
  def destroy
    @repo = Repo.find(params[:id])
    @repo.destroy

    respond_to do |format|
      format.html { redirect_to repos_url }
    end
  end

end

app/helpers/repo_helper.rb
module RepoHelper
  
  # View Helper
  def time_ago_in_less_precise_words(last_updated)
    # less precise than time_ago_in_words()
    td = Time.now - last_updated
    
    if td < (61*60)
      return "1 hour"
    elsif td < (121*60)
      return "2 hours"
    elsif td < (24*60*60)
      return "24 hours"
    elsif td < (3*24*60*60)
      return "3 days"
    elsif td < (7*24*60*60)
      return "1 week"
    elsif td < (14*24*60*60)
      return "2 weeks"
    elsif td < (31*24*60*60)
      return "1 month"
    elsif td < (62*24*60*60)
      return "2 months"
    elsif td < (93*24*60*60)
      return "3 months"
    elsif td < (183*24*60*60)
      return "6 months"  
    elsif td < (365*24*60*60)
      return "1 year"
    elsif td < (2*365*24*60*60)
      return "2 years"
    elsif td < (3*365*24*60*60)
      return "3 years"
    elsif td < (5*365*24*60*60)
      return "5 years"      
    elsif td < (10*365*24*60*60)
      return "1 decade"
    elsif td > (10*365*24*60*60)
      return "1 century"
    else
    end
  end
  
  # View Helper
  def activity_light(last_updated)
    time_difference = Time.now - last_updated
    
    if time_difference < (18*24*60*60)
      return "activity awesomely_active"
    elsif time_difference < (38*24*60*60)
      return "activity greatly_active"
    elsif time_difference < (93*24*60*60)
      return "activity active"
    elsif time_difference < (185*24*60*60)
      return "activity less_active"
    elsif time_difference > (185*24*60*60)
      return "activity not_active"
    end
  end
  
end

app/views/repo/_form.html.erb
<%= form_for(@repo) do |f| %>
  <% if @repo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repo.errors.count, "error") %> prohibited this repo from being saved:</h2>

      <ul>
      <% @repo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :owner %><br />
    <%= f.text_field :owner %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :watchers %><br />
    <%= f.number_field :watchers %>
  </div>
  <div class="field">
    <%= f.label :forks %><br />
    <%= f.number_field :forks %>
  </div>
  <div class="field">
    <%= f.label :html_url %><br />
    <%= f.text_field :html_url %>
  </div>
  <div class="field">
    <%= f.label :last_updated %><br />
    <%= f.datetime_select :last_updated %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repo/edit.html.erb
<h1>Editing repo</h1>

<%= render 'form' %>

<%= link_to 'Show', @repo %> |
<%= link_to 'Back', repos_path %>

app/views/repo/index.html.erb
<h1>Repofinder - Category <%= @cat_name %></h1>
<p>V 0.0.3 - 25. Januar 2012</p>

<a href="/category">Categories</a>

<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

	
<%= render(partial: "shared/repo", collection: @repos ) %>

<%= render(partial: "shared/add_repo" )%>

app/views/repo/new.html.erb
<h1>New repo</h1>

<%= render 'form' %>

<%= link_to 'Back', repos_path %>

app/views/repo/show.html.erb
<p id="notice"><%= notice %></p>

	<%= render(partial: "shared/repo", object: @repo) %>

	<form action="/tag" method="post">
		<input type="hidden" name="repo_id" value="<%= @repo.id %>" />
		<input type="text" size="8" name="tag_name" / autocomplete="off">
		<input type="submit" value="Tag: Add" name="add_category">
		<input type="submit" value="Tag: Remove" name="remove_category">
		<input type="submit" value="Framework: Add" name="add_framework">
		<input type="submit" value="Framework: Remove" name="remove_framework">
		<input type="submit" value="Language: Add" name="add_language">
		<input type="submit" value="Language: Remove" name="remove_language">
	</form>	
	
	<%= render(partial: "shared/repo", collection: @alternatives ) %>
	
<%= link_to 'Edit', edit_repo_path(@repo) %> |
<%= link_to '&lsaquo; Overview'.html_safe, repo_index_path %>

app/views/repo/tag_repo.html.erb
<%= @url.inspect %>


<h1>Thanks for bringing  to Discovery!</h1>

<h3>You can easily add some tags for it, if you like:</h3>

	<form action="/tag" method="post">
		<input type="hidden" name="repo_id" value="" />
		<input type="text" size="8" name="tag_name" / autocomplete="off">
		<input type="submit" value="Tag: Add" name="add_category">
		<input type="submit" value="Tag: Remove" name="remove_category">
		<input type="submit" value="Framework: Add" name="add_framework">
		<input type="submit" value="Framework: Remove" name="remove_framework">
		<input type="submit" value="Language: Add" name="add_language">
		<input type="submit" value="Language: Remove" name="remove_language">
	</form>